// @ts-expect-error generated by OpenNext build
import openNextWorker from "./.open-next/worker.js";
import { syncAiraloPackages } from "./lib/airalo/sync-packages";
import type { AppEnv } from "./lib/env";

const worker = {
  async fetch(request: Request, env: AppEnv, ctx: ExecutionContext) {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: AppEnv, ctx: ExecutionContext) {
    ctx.waitUntil(
      (async () => {
        try {
          const result = await syncAiraloPackages(env);
          console.log(
            `[Scheduled Package Sync] ${controller.cron}: ${result.totalSynced} packages across ${result.activeCountries} countries`
          );
        } catch (error) {
          console.error("[Scheduled Package Sync] Failed:", error);
          throw error;
        }
      })()
    );
  },
};

export default worker;
